const userData = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "Sincere@april.biz",
    image: "/assets/1.jpeg",
    catchPhrase: "Multi-layered client-server neural-net",
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Antonette",
    email: "Shanna@melissa.tv",
    image: "/assets/2.jpeg",
    catchPhrase: "Proactive didactic contingency",
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "Samantha",
    email: "Nathan@yesenia.net",
    image: "/assets/3.jpeg",
    catchPhrase: "Face to face bifurcated interface",
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "Julianne.OConner@kory.org",
    image: "/assets/4.jpeg",
    catchPhrase: "Switchable contextually-based project",
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "Lucio_Hettinger@annie.ca",
    image: "/assets/5.jpeg",
    catchPhrase: "Multi-tiered zero tolerance productivity",
  },
  {
    id: 6,
    name: "Mrs. Dennis Schulist",
    username: "Leopoldo_Corkery",
    email: "Karley_Dach@jasper.info",
    image: "/assets/6.jpeg",
    catchPhrase: "User-centric fault-tolerant solution",
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    username: "Elwyn.Skiles",
    email: "Telly.Hoeger@billy.biz",
    image: "/assets/7.jpeg",
    catchPhrase: "Synchronised bottom-line interface",
  },
  {
    id: 8,
    name: "Nicholas Runolfsdottir V",
    username: "Maxime_Nienow",
    email: "Sherwood@rosamond.me",
    image: "/assets/8.jpeg",
    catchPhrase: "Configurable multimedia task-force",
  },
  {
    id: 9,
    name: "Glenna Reichert",
    username: "Delphine",
    email: "Chaim_McDermott@dana.io",
    image: "/assets/9.jpeg",
    catchPhrase: "Implemented secondary concept",
  },
  {
    id: 10,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    image: "/assets/10.jpeg",
    catchPhrase: "Centralized empowering task-force",
  },
];
export default userData;
